import type { Metadata } from 'next';
import Header from '@/components/header/header';
import styles from './layout.module.css';
import './global.css';

export const metadata: Metadata = {
  title: 'Event Planner App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <div className={styles.container}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
